### ISSUE TITLE
Nodes for control

### ISSUE THREAD

**Issue by paleym** [Edziu1996/ExtraPermissions#1]
Hello,

I just started looking at your plugin, and it seems great!

I do have a question about documentation.  If there is a node to control who can set ranks, what is it?

Can there be a command for viewing the rank and information about a player and rank, such as /experm group <group>  and /experm player <>?

Thank you for developing this!

**Comment by Edziu1996** [comment]
That's what you mean:
/experm info player < player_name >
/experm info group < rank_name >

**Comment by paleym** [comment]
Are those implemented yet?  I just updated to 0.3.0 and NameAPI-0.2.0

And as far as the nodes for controlling who can promote?

So far in my set up (pretty early on) I have the following ranks:
Default
Builder
Moderator
Admin
Owner

And I want the Moderators to be able to move people in and out of Builder / Default, but not into or out of Moderator or higher.  The same for Admin to move others in and out of Moderator and below, but not admin.  As far as my testing goes, it seems to be that anyone with ExtraPerm.experm.player can move anyone into any rank.

**Comment by Edziu1996** [comment]
Interesting'll do it after finishing the command "/experm info"

**Comment by paleym** [comment]
Thank you!

**Comment by Edziu1996** [comment]
I did and to give rank must have permission eg .: "experm.experm.group.vip"

**Comment by paleym** [comment]
'experm.experm' or ExtraPerm.experm...'

**Comment by Edziu1996** [comment]
Give Moderator permissions:
- extraperm.extraperm.group.builder
- extraperm.extraperm.group.default (comming soon)

**Comment by 2iguys** [comment]
is it possible to set it up so that it is extraperm.extraperm.group.[groupname]
(which includes inheritances of that group)

so for example if i have mod inherit builder and I give someone extraperm.extraperm.group.mod then they can move anyone into the mod->builder->member->user ranks

**Comment by 2iguys** [comment]
as well, having a command that does ( /experm groups ) to list all the groups available would be nice

**Comment by Edziu1996** [comment]
"/experm groups" = "/experm info group"

**Comment by Edziu1996** [comment]
I'm done. If you want someone to give all powers give "extraperm": true

**Comment by 2iguys** [comment]
ok, I am testing right now
I will send results

**Comment by paleym** [comment]
So in testing I am finding that it works but not fully.

Pastebin of ranks file: http://pastebin.com/SU2jbX5P

As a defualt I cannot do the command at all, as a builder I cannot do the command at all, but as a moderator I can move myself around to any rank.

**Comment by 2iguys** [comment]
There is a new release, maybe try updating?

**Comment by paleym** [comment]
From an hour ago? I did put that in.

**Comment by 2iguys** [comment]
4.6
if you aren't on that version it could be the reason

**Comment by paleym** [comment]
Confirming, I am on 0.4.6 and still have that issue...

**Comment by Edziu1996** [comment]
As the name ranks write in lowercase in inheritance also lowercase!

**Comment by Edziu1996** [comment]
The size of the letters is very important and therefore inheritance do not work

**Comment by paleym** [comment]
Fixed that, I had done that but it most not have saved.  That still doesn't explain why as a moderator I can move myself into admin?

**Comment by Edziu1996** [comment]
extraperm.experm.player.admin: false

**Comment by paleym** [comment]
'extraperm.experm.group.owner: false
Do not edit the owner.

extraperm.experm.group.admin: false
Do not edit the admin.'

this prevents people from editing the groups?

**Comment by Edziu1996** [comment]
yes, structure:
extraperm.experm.group.< name >.< option > or extraperm.experm.group.< name >.< option >.< value >

option: prefix, suffix, permission, inheritance, remove

if option = remove
value: prefix, suffix, permission, inheritance

**Comment by Edziu1996** [comment]
Everything is on the wiki or forums.spongepowered.org

**Comment by 2iguys** [comment]
if I start a spongeforge server, I will try this again, just as a helpful tip, you should put this into your code so that people don't get confused. **.equalsIgnoreCase**

**Comment by 2iguys** [comment]
if(args[0].equalsIgnoreCase("add")){
				if (sender.hasPermission("oasiscast.staff.add")) {
					if (args.length == 4) {
						plugin.getConfig().set(args[1] + ".Name", args[2]);
						plugin.getConfig().set(args[1] + ".Text", args[3]);
						plugin.saveConfig();
						sender.sendMessage(ChatColor.GREEN
								+ "Successfully added!");
						return true;
					} else {
						sender.sendMessage(ChatColor.RED
								+ "/cast add cmd_name displayname textcolor");
						return false;

THIS IS AN EXAMPLE OF USING IT
