### ISSUE TITLE
Plugin not working after using config

### ISSUE THREAD

**Issue by NickSackett** [Edziu1996/ExtraPermissions#10]
So when ever i first install the plugin it shows that the /experm command is there but when i stop the server to update the config and restart the server, it acts as if there is no command/plugin.

**Comment by Edziu1996** [comment]
What version of the server and plugin?

**Comment by NickSackett** [comment]
0.6.2 version server 1.8.9

**Comment by Edziu1996** [comment]
You enter a list of all plugins?

**Comment by NickSackett** [comment]
of all my plugins orrr?

**Comment by Edziu1996** [comment]
You enter logs?

**Comment by NickSackett** [comment]
yes

**Comment by Edziu1996** [comment]
Send me my plugin configurations and logs

**Comment by NickSackett** [comment]
it does not support the type of file also i wouldnt understand where your logs would be

**Comment by Edziu1996** [comment]
E-Mail: edziu1996@gmail.com

**Comment by NickSackett** [comment]
where would i find your logs and do you mean the plugin config file found in filezilla?

**Comment by Edziu1996** [comment]
Logs: server->logs
Config: server -> config -> extraperm

**Comment by NickSackett** [comment]
alright

**Comment by Edziu1996** [comment]
[NameAPI](https://github.com/Edziu1996/NameAPI/releases) is installed?

**Comment by NickSackett** [comment]
yes

**Comment by Edziu1996** [comment]
It is not installed!
Download [here](https://github.com/Edziu1996/NameAPI/releases/download/v0.3.1/NameAPI-0.3.1.jar).

**Comment by NickSackett** [comment]
ill try again but i had it installed ive allready tried to do this all a few times i keep switching perm plugins but to no avail

**Comment by NickSackett** [comment]
what is the command to add players to groups the complete command?
-

**Comment by Edziu1996** [comment]
How do you type them?

**Comment by NickSackett** [comment]
if your asking if that is what i am asking then yes, and why would it now say the command /experm exist when i edit the ranks?

**Comment by Edziu1996** [comment]
Manual edit ranks: server -> config -> extraperm -> ranks.conf

Edit rank prefix: /experm group < rank_name > prefix < value >
Edit rank suffix: /experm group < rank_name > suffix< value >
Edit rank permissions: /experm group < rank_name > permission < permission_name > < value >
Edit rank inheritance: /experm group < rank_name > inheritance < rank_name >

Edit player prefix: /experm player < player_name > prefix < value >
Edit player suffix: /experm player < player_name > suffix< value >
Edit player rank: 
+ /experm player < player_name > rank < rank_name>
+ /experm player < player_name > rank < rank_name> -t < ms/s/m/h/d/mo/y > < value >

**Comment by NickSackett** [comment]
what do i do with this information?

**Comment by Edziu1996** [comment]
All entered commands work.

**Comment by NickSackett** [comment]
"argument not valid"

**Comment by Edziu1996** [comment]
What is the command you are trying to type?

**Comment by NickSackett** [comment]
trying to add player to a group

**Comment by Edziu1996** [comment]
You are using, for example: /extraperm player edziu96 rank admin

**Comment by NickSackett** [comment]
ok so when i type it says the world name next to the prefix any advice on how to fix that?

**Comment by Edziu1996** [comment]
Edit in file: server -> config -> extraperm -> config.conf -> chat -> formula

**Comment by NickSackett** [comment]
what would i take out

**Comment by Edziu1996** [comment]
Default: world name, group prefix, player prefix, player name, player suffix, group suffix

**Comment by NickSackett** [comment]
i dont see this

**Comment by Edziu1996** [comment]
What you want to have the order?

**Comment by NickSackett** [comment]
yes

**Comment by NickSackett** [comment]
a file maybe i just want to see what it would be without the world name on it

**Comment by Edziu1996** [comment]
How would you like to have it arranged?

**Comment by NickSackett** [comment]
<prefix> name

**Comment by Edziu1996** [comment]
Group prefix, player name
formula="%rank_prefix% %player%: "

**Comment by NickSackett** [comment]
can i get rid of the rest of the text there or?

**Comment by Edziu1996** [comment]
**If the line starts with "#" it can be removed**



chat {
    formula="%rank_prefix% %player%: "
}
lang="en_US"

**Comment by Edziu1996** [comment]
You can use color.

**Comment by NickSackett** [comment]
really also this didnt work
ill send what i have

**Comment by NickSackett** [comment]
chat {
    #%rank_prefix%,%rank_suffix% - rank prefix and suffix; %player_prefix%,%player_suffix% - player suffix and prefix; %player% - player name
    formula=%rank_prefix% %player%"
}
lang="en_US"

**Comment by NickSackett** [comment]
even after removing that #line no change occured

**Comment by Edziu1996** [comment]
chat {
    formula="%rank_prefix% %player%: "
}
lang="en_US"


It works, I checked.
What time is it where you are?

**Comment by NickSackett** [comment]
5:21pm

**Comment by NickSackett** [comment]
ok so that worked now how does the color work and another issue is i put permissions under the permissions in ranks but it says i dont have permission

**Comment by Edziu1996** [comment]
Give me a command, which you type?

**Comment by NickSackett** [comment]
its an essentials plugin actually the essentialscmd plugin for example /fly or /heal

**Comment by Edziu1996** [comment]
If you add to a group permission with the command, the player with the group must relogin

**Comment by Edziu1996** [comment]
Teraz idę spać. U mnie jest teraz godzina 12:31 AM
00:32 2016-08-14

**Comment by NickSackett** [comment]
i added through ftp
i used /extraperm reload

**Comment by NickSackett** [comment]
what?

**Comment by NickSackett** [comment]
the error is now occuring after i type any of your commands it say unknown command

**Comment by Edziu1996** [comment]
As I tested now it all works

**Comment by NickSackett** [comment]
eveb my prefixes are not showing up anymore name api and extraperms are both still installed

**Comment by Edziu1996** [comment]
Send me a log and check if the plugins do not collide.

**Comment by NickSackett** [comment]
email?

**Comment by Edziu1996** [comment]
yes

**Comment by NickSackett** [comment]
ok

**Comment by Edziu1996** [comment]
I send fixed

**Comment by NickSackett** [comment]
it is saying that the plugin is unknown as if its not in the server, but indeed it is in there

**Comment by Edziu1996** [comment]
Reload server?

**Comment by NickSackett** [comment]
ok even tho that works the permissions do not work in the groups,

**Comment by Edziu1996** [comment]
I send fixed

**Comment by NickSackett** [comment]
when i add another rank for example mod or 0wner and i add player it doesnt show prefix after i edit it

**Comment by Edziu1996** [comment]
Send me a file ranks.conf and I'll correct it

**Comment by NickSackett** [comment]
ok

**Comment by Edziu1996** [comment]
For the future:
+ add permission
 - "permission"=true
+ block permission
 - "permission"=false

**Comment by Edziu1996** [comment]
I send fixed file ranks.conf

**Comment by NickSackett** [comment]
ok my last questions you said yesterday that you can use colors how would one do that and also, does each permission need to be followed by a " "

**Comment by Edziu1996** [comment]
For example,
prefix="&a[Admin]&r"

Permissions of the dots must be in a " " and end on **=true** or **=false**
[Colors -Kolory.txt](https://github.com/Edziu1996/ExtraPermissions/files/417269/Colors.-Kolory.txt)

**Comment by NickSackett** [comment]
what does permission of the dots

**Comment by Edziu1996** [comment]
For example:
+ permissions: extraperm=true
 - need not be in '' "
+ permissions: "essentialcmds.invsee.use"=true
 - must be in '' "

**Comment by Edziu1996** [comment]
Plugin was updated!

**Comment by Edziu1996** [comment]
In the "ExtraPerissions v0.7.2" everything should work
