### ISSUE TITLE
Colored prefixes don't appear to be working.

### ISSUE THREAD

**Issue by tenten8401** [Edziu1996/ExtraPermissions#11]
This may be a complete noob question here, but I was setting up permissions and prefixes look like this.
![Picture of this crap](http://i.imgur.com/hBPcODF.png)

My config is located here: http://hastebin.com/ewerudixux.cpp

Please tell me what I'm doing wrong or if this needs to be fixed.

**Comment by tenten8401** [comment]
May I mention: I'm using these plugins:
`Plugins (54): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, CodeChicken Core, Not Enough Items, OpenComputers (Core), Backpacks!, SpongeForge, ItemBlacklist, NoXray, Biomes O' Plenty, Brandon's Core, Chameleon, ChickenChunks, Chisel, MCMultiPart, Chisels & Bits, IndustrialCraft 2, Compact Solar Arrays, Draconic Evolution, EconomyLite, EnderCore, Waila, Ender IO, EnderStorage, EssentialCmds, ExtraPermissions, ExtraUtils2, GriefPrevention, Inventory Tweaks, Iron Chest, Just Enough Items, MalisisCore, MalisisDoors, Mantle, Mekanism, MekanismGenerators, MekanismTools, NameAPI, Nether Metals, OpenComputers, Prism, Project Portals, RankUpper, RFTools, RFTools Dimensions, Router Reborn, Discord Bridge, Storage Drawers, Super Crafting Frame, Tinkers' Construct, WorldEdit, UniDict`

**Comment by Edziu1996** [comment]
Logs?

**Comment by tenten8401** [comment]
Updated to the latest build of sponge and it worked great. Sorry for bothering you.

**Comment by tenten8401** [comment]
Scratch that, it broke AGAIN after a restart.

**Comment by Edziu1996** [comment]
Plugin was updated!

**Comment by Edziu1996** [comment]
In the ExtraPerissions v0.7.2 everything should work
