### ISSUE TITLE
Github / In-game Information

### ISSUE THREAD

**Issue by paleym** [Edziu1996/ExtraPermissions#2]
It would be nice to get a complete list of all nodes / commands.  Github supports this with the 'Wiki' area, and if you are adding new commands, can they get listed there and in-game under the /experm command?

**Comment by 2iguys** [comment]
agreed

**Comment by Edziu1996** [comment]
Still I not finished my commands and not compiled plugin.

**Comment by Edziu1996** [comment]
Wiki has been created
