### ISSUE TITLE
Colors in chat...

### ISSUE THREAD

**Issue by 2iguys** [Edziu1996/ExtraPermissions#4]
the plugin I use (essentialcmds) has a color chat feature, it doesn't want to work in chat.  I assume it's an api thing, i can make the nickname have a color and it makes chat colored but i can't use &a-b and &1-9

**Comment by 2iguys** [comment]
in chat

**Comment by paleym** [comment]
What essentialscmds are you using?  I have:

Forge: 1.8.9-11.15.1.1722
Sponge 1722-3.1.0-BETA.1110
EssentialCmds-7.2d

and I can do colors in chat and nicks

**Comment by 2iguys** [comment]
same thing.
it doesn't let me with 

essentialcmds-7.2d
extrapermissions V.0.3.0
NameApi V.0.2.0

it wont let it work

**Comment by 2iguys** [comment]
![2016-01-28_13 38 29](https://cloud.githubusercontent.com/assets/9800376/12654968/94ef9434-c5c4-11e5-9f84-d3d9c92dd394.png)

**Comment by paleym** [comment]
![color](https://cloud.githubusercontent.com/assets/5383960/12655048/49875f3c-c5b4-11e5-9878-b8371e4fc79c.PNG)

**Comment by paleym** [comment]
Now my problem is I either can't figure out the node for the /nick command or am adding it incorrectly, I have to do it through console atm.

I tried "essentialcmds.nick.use"=true

**Comment by 2iguys** [comment]
i have the nameapi nick enabled

**Comment by 2iguys** [comment]
i think its blocking the essentialscmds one

**Comment by 2iguys** [comment]
let me try permnodes to get it to work

**Comment by 2iguys** [comment]
do you have nameapi and the new version of extrapermissions installed?

**Comment by paleym** [comment]
Yes, what are the node(s) for the nameapi?

**Comment by 2iguys** [comment]
nameapi.nick

**Comment by paleym** [comment]
Thanks

**Comment by 2iguys** [comment]
if there is a way that the color could stop after the nick ends, that would be good

**Comment by Edziu1996** [comment]
&r - reset kolor

**Comment by 2iguys** [comment]
your name api overwrites the colors that chat recieves.

**Comment by 2iguys** [comment]
it seems essentialcmds' pemission nodes don't work...

**Comment by 2iguys** [comment]
I gave my default rank essentialcmds.tpa.use and when I do /tpa it says "you don't have permission to use this command"

**Comment by Edziu1996** [comment]
It works for me. You have entered the permissions as "essentialcmds.tpa.use"=true

**Comment by 2iguys** [comment]
does it need the ""'s in game?

**Comment by Edziu1996** [comment]
I check the file with ranks?

**Comment by 2iguys** [comment]
I tried all sorts, nothing is working.

**Comment by Edziu1996** [comment]
Show maybe something I was wrong

**Comment by 2iguys** [comment]
user {
    default=true
    permissions {
        "ExtraPerm.build"=true
        default=true
        "essentialcmds.color.chat.use"=true
        "essentialcmds.home.delete"=true
        "essentialcmds.home.list"=true
        "essentialcmds.home.set"=true
        "essentialcmds.home.use"=true
        "essentialcmds.spawn.use"=true
        "essentialcmds.tpa.use"=true
        "experm.build"=true
        "sponge.plugins"=true
        "voteright.simulate"=true
    }
    prefix="&7[&bGuest&7]&r"
}

**Comment by Edziu1996** [comment]
Exit and go to the server

**Comment by 2iguys** [comment]
ok?

**Comment by 2iguys** [comment]
then what?

**Comment by Edziu1996** [comment]
It should work

**Comment by 2iguys** [comment]
welp it doesn't seem to be working... no permissions are registering...

**Comment by 2iguys** [comment]
other than spawn

**Comment by Edziu1996** [comment]
It works for me. Apart from chat

**Comment by 2iguys** [comment]
... hmm

**Comment by 2iguys** [comment]
I i will add another plugin with perm nodes and try that later

**Comment by Edziu1996** [comment]
I fixed chat and permissions

**Comment by 2iguys** [comment]
ok, I will test it out

**Comment by 2iguys** [comment]
![2016-01-28_20 22 55](https://cloud.githubusercontent.com/assets/9800376/12664388/22bae236-c5fd-11e5-98c8-023731dd3d7b.png)

**Comment by 2iguys** [comment]
thats what i get when i do /nameapi:nick &a2iguys 2iguys

**Comment by 2iguys** [comment]
permissions work

**Comment by Edziu1996** [comment]
Already fix it.
To change the nick to someone you have to have permissions:
"nameapi.nick.others" and "nameapi.nick.use"

**Comment by 2iguys** [comment]
Ok I will test it out in a few hours :)
