### ISSUE TITLE
Permissions not functioning?

### ISSUE THREAD

**Issue by paleym** [Edziu1996/ExtraPermissions#5]
Updated to the 0.4.2 and now I can't do commands in game? console says I am the 'owner' rank, and that the rank has the permissions, but it doesn't seem to work?

ranks - http://pastebin.com/6h8pSq2X

players.conf -
ce43ae26-4624-4ff5-xxxx-xxxx8ac6xxxx {
    rank=Admin
}

![servercommands](https://cloud.githubusercontent.com/assets/5383960/12682911/3a845d7c-c673-11e5-9dda-c1fec40f9cfb.PNG)

**Comment by 2iguys** [comment]
where is the issue there? I don't see anything that says "You don't have permisson to use that command" or anything that indicates it being broken...

**Comment by Edziu1996** [comment]
if moderator {..}
it inheritance=moderator
case sensitive!

**Comment by Edziu1996** [comment]
I fixed it, you can test
