### ISSUE TITLE
List Groups

### ISSUE THREAD

**Issue by 2iguys** [Edziu1996/ExtraPermissions#6]
Can there be a command that is like 
/experm list groups
to list all the available groups

and /experm list players [groupname]
to see what players are in what group.

**Comment by 2iguys** [comment]
ok and the one where you can see the list of players in a group?

**Comment by paleym** [comment]
If it exists, I couldn't figure it out.

**Comment by 2iguys** [comment]
no, I looked around it isn't there, but it should be

**Comment by 2iguys** [comment]
Like it would be a nice feature

**Comment by paleym** [comment]
Sorry to put this here, but just easier: 2iguys, did you ever find a node dump plugin? I looked and would love to have one but I cannot find any.

**Comment by 2iguys** [comment]
I will take a peek around.

**Comment by Edziu1996** [comment]
I already create it

**Comment by 2iguys** [comment]
created what, the /experm list players [groupname] or something like it

**Comment by 2iguys** [comment]
ok, new release or 4.6

**Comment by Edziu1996** [comment]
0.4.7

**Comment by 2iguys** [comment]
ok
updating now

**Comment by 2iguys** [comment]
is it uploaded as a release?

**Comment by Edziu1996** [comment]
yes

**Comment by 2iguys** [comment]
don't see the release 0.4.7 most resent is 0.4.6 still

**Comment by Edziu1996** [comment]
already

**Comment by 2iguys** [comment]
ok

**Comment by 2iguys** [comment]
Testing now

**Comment by 2iguys** [comment]
![2016-01-30_11 06 22](https://cloud.githubusercontent.com/assets/9800376/12696813/aabbf00e-c741-11e5-8513-c30f63dcb9bd.png)

**Comment by 2iguys** [comment]
needs to have a limit as to how many names can be listed.

**Comment by 2iguys** [comment]
actually
after running the command for all the groups that I am not in, it says that every time

**Comment by Edziu1996** [comment]
If no one is, so it shows

**Comment by 2iguys** [comment]
ok

**Comment by 2iguys** [comment]
I tested this even with a new player this is the result

**Comment by 2iguys** [comment]
![2016-01-30_11 27 34](https://cloud.githubusercontent.com/assets/9800376/12696941/a928ff04-c744-11e5-8438-da6ebdf7b14f.png)

**Comment by Edziu1996** [comment]
It works only the name changing table

**Comment by 2iguys** [comment]
what do you mean?

**Comment by Edziu1996** [comment]
=========== Ranks: ===========
exchange for
========== Players from <group name>: =======

**Comment by 2iguys** [comment]
(/experm list players user) is that correct?

**Comment by Edziu1996** [comment]
yes

**Comment by 2iguys** [comment]
my name is the only one that comes up, but there are 2 players there.

**Comment by Edziu1996** [comment]
A revised version was sent

**Comment by Edziu1996** [comment]
It shows only the players registered.
But now it shows players not registered as the default group.

**Comment by 2iguys** [comment]
ok, was away, will test it now

**Comment by 2iguys** [comment]
can you release it as an update?

**Comment by Edziu1996** [comment]
It's already.

**Comment by 2iguys** [comment]
ok

**Comment by 2iguys** [comment]
there is no new version showing

**Comment by Edziu1996** [comment]
ExtraPermissions v0.4.7
It was a small patch so do not changed version

**Comment by 2iguys** [comment]
oh

**Comment by 2iguys** [comment]
Still having the issue
when I do /experm list players user it doesn't show who is in the group other than me

**Comment by 2iguys** [comment]
It should be looking at the players file and picking the players with the group user then displaying them in chat

**Comment by 2iguys** [comment]
let me try something then I will get back to you

**Comment by 2iguys** [comment]
Ok it does work now
Thank you

**Comment by 2iguys** [comment]
I just verified that there were actually other players showing in the players file, I added one and it showed up

**Comment by 2iguys** [comment]
![2016-01-30_17 05 27](https://cloud.githubusercontent.com/assets/9800376/12698777/f1a535e8-c773-11e5-9dcc-b31b402e30a0.png)
